# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2024_10_23_002029) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "active_admin_comments", force: :cascade do |t|
    t.string "namespace"
    t.text "body"
    t.string "resource_type"
    t.bigint "resource_id"
    t.string "author_type"
    t.bigint "author_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["author_type", "author_id"], name: "index_active_admin_comments_on_author_type_and_author_id"
    t.index ["namespace"], name: "index_active_admin_comments_on_namespace"
    t.index ["resource_type", "resource_id"], name: "index_active_admin_comments_on_resource_type_and_resource_id"
  end

  create_table "admin_users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["email"], name: "index_admin_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_admin_users_on_reset_password_token", unique: true
  end

  create_table "barcos", force: :cascade do |t|
    t.string "nombre"
    t.string "nave"
    t.boolean "barandas"
    t.boolean "colectores"
    t.boolean "vtolva1"
    t.boolean "vtolva2"
    t.boolean "al1"
    t.boolean "al2"
    t.boolean "compresorm"
    t.boolean "cabezalm"
    t.boolean "cabezald"
    t.boolean "polines"
    t.boolean "redaire"
    t.boolean "motoresbc03"
    t.boolean "techotolva"
    t.boolean "greating"
    t.boolean "alumbrado"
    t.boolean "caseta"
    t.boolean "ccmmuelle"
    t.boolean "c18"
    t.boolean "c19"
    t.integer "numero"
    t.text "observaciones"
    t.string "empresa"
    t.string "varios"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "checklists", force: :cascade do |t|
    t.string "nombre"
    t.string "equipo"
    t.string "operativo"
    t.string "horometro"
    t.boolean "c1"
    t.boolean "c2"
    t.boolean "c3"
    t.boolean "c4"
    t.boolean "c5"
    t.boolean "c6"
    t.boolean "c7"
    t.boolean "c8"
    t.boolean "c9"
    t.boolean "c10"
    t.boolean "c11"
    t.boolean "c12"
    t.boolean "c13"
    t.boolean "c14"
    t.boolean "c15"
    t.boolean "c16"
    t.boolean "c17"
    t.boolean "c18"
    t.boolean "c19"
    t.integer "combustible"
    t.integer "acmotor"
    t.integer "achidraulico"
    t.integer "actrans"
    t.integer "acatf"
    t.integer "acnuto"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "truck_id"
    t.index ["truck_id"], name: "index_checklists_on_truck_id"
  end

  create_table "entregas", force: :cascade do |t|
    t.date "fecha"
    t.string "nombre"
    t.string "tipo"
    t.string "responsable"
    t.integer "antiguedad"
    t.string "observaciones"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "planta"
  end

  create_table "envasadoras", force: :cascade do |t|
    t.integer "stock_sacosespecial"
    t.integer "stock_sacosextra"
    t.integer "stock_bigbagespaecial"
    t.integer "stock_bigbagextra"
    t.integer "stock_bigbagplus"
    t.integer "stock_bigbagsuper"
    t.integer "produccion_haver"
    t.integer "horas_disphaver"
    t.integer "horas_efectivahaver"
    t.integer "produccion_ventomatic"
    t.integer "horas_dispventomatic"
    t.integer "horas_efectivaventomatic"
    t.integer "programa_especialsacos"
    t.integer "programa_extrasacos"
    t.integer "programa_especialbigbag"
    t.integer "programa_extrabigbag"
    t.integer "programa_extrabigbag1t"
    t.integer "programa_plusbigbag"
    t.integer "programa_superbigbag"
    t.integer "despacho_especialsacos"
    t.integer "despacho_extrasacos"
    t.integer "despacho_especialbigbag"
    t.integer "despacho_extrabigbag"
    t.integer "despacho_extrabigbag1t"
    t.integer "despacho_plusbigbag"
    t.integer "despacho_superbigbag"
    t.integer "medida1_silo19"
    t.integer "medida2_silo19"
    t.integer "medida1_silo20"
    t.integer "medida2_silo20"
    t.integer "medida1_silo21"
    t.integer "medida2_silo21"
    t.integer "medida1_silo22"
    t.integer "medida2_silo22"
    t.integer "medida_silo27"
    t.integer "medida_silo28"
    t.integer "medida_tolva5s28"
    t.integer "medida_tolva1vento"
    t.integer "medida_tolva2vento"
    t.integer "medida_tolva3vento"
    t.integer "medida_tolva1bigbag"
    t.integer "medida_tolva2bigbag"
    t.integer "medida_tolva1s3000"
    t.integer "medida_tolva4s3000"
    t.string "medida_tolva5s3000"
    t.string "producto_tolva5s28"
    t.string "producto_tolva1vento"
    t.string "producto_tolva2vento"
    t.string "producto_tolva3vento"
    t.string "producto_tolva1bigbag"
    t.string "producto_tolva2bigbag"
    t.string "producto_tolva1s3000"
    t.string "producto_tolva4s3000"
    t.string "producto_tolva5s3000"
    t.integer "programa_manthaver"
    t.integer "ejecutado_manthaver"
    t.integer "programa_mantvento"
    t.integer "ejecutado_mantvento"
    t.integer "programa_mantbigbag"
    t.integer "ejecutado_mantbigbag"
    t.integer "programa_mantgranel"
    t.integer "ejecutado_mantgranel"
    t.integer "programa_mantplanta1"
    t.integer "ejecutado_mantplanta1"
    t.integer "programa_mantenv"
    t.integer "ejecutado_mantenv"
    t.integer "adicional_manthaver"
    t.integer "adicional_mantvento"
    t.integer "adicional_mantbigbbag"
    t.string "adicional_mantgranel"
    t.integer "adicional_mantp1"
    t.integer "adicional_mantenv"
    t.string "obs_manthaver"
    t.string "obs_mantvento"
    t.string "obs_mantbigbag"
    t.string "obs_mantgranel"
    t.string "obs_mantp1"
    t.string "obs_mantenv"
    t.string "linea_tarearelevante"
    t.string "ot_tarearelevante"
    t.string "descripcion_tarearelevante"
    t.string "tipo_fallarelevante"
    t.integer "hora_fallarelevante"
    t.string "descripcion_fallarelevante"
    t.integer "descarga_materiaprima"
    t.integer "respaldo_descargamateriaprima"
    t.integer "excavadora"
    t.integer "camion_tolva"
    t.integer "barredora"
    t.integer "bobcat"
    t.integer "horquilla_serv"
    t.integer "horquilla_haver"
    t.integer "horquilla_vento"
    t.integer "horquilla_cargabigbag"
    t.integer "horquilla_llenadobigbag"
    t.integer "horquilla_respaldo7t"
    t.integer "horquilla_respaldo3t"
    t.integer "cargador_descargacaliza"
    t.integer "cargador_descargapuzolana"
    t.integer "cargador_respaldo"
    t.integer "cargador_patio"
    t.text "observaciones"
    t.date "fecha"
    t.string "observacion_prodhaver"
    t.string "observacion_prodvento"
    t.integer "num_adicional"
    t.integer "num_adicional2"
    t.integer "num_adicional3"
    t.string "adicional"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "equipos", force: :cascade do |t|
    t.string "nombre"
    t.string "operador"
    t.integer "horometro"
    t.string "c1"
    t.string "c2"
    t.string "c3"
    t.string "c4"
    t.string "c5"
    t.string "c6"
    t.string "c7"
    t.string "c8"
    t.string "c9"
    t.string "c10"
    t.string "c11"
    t.string "c12"
    t.string "c13"
    t.string "c14"
    t.string "c15"
    t.string "c16"
    t.string "c17"
    t.string "c18"
    t.string "c19"
    t.string "c20"
    t.string "c21"
    t.string "c22"
    t.string "c23"
    t.string "c24"
    t.string "c25"
    t.string "c26"
    t.string "c27"
    t.string "c28"
    t.string "c29"
    t.string "c30"
    t.text "comentarios"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "truck_id"
    t.index ["truck_id"], name: "index_equipos_on_truck_id"
  end

  create_table "gastos", force: :cascade do |t|
    t.date "fecha"
    t.integer "rend"
    t.string "tipo"
    t.integer "num"
    t.string "descripcion"
    t.integer "valor"
    t.integer "iva"
    t.integer "neto"
    t.string "cc"
    t.string "resp"
    t.string "familia"
    t.integer "cot"
    t.string "aprobado"
    t.string "estado"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "tipo_documento"
    t.integer "folio"
    t.string "emisor"
    t.string "razon_social_emisor"
    t.string "emision"
    t.integer "monto_neto"
    t.integer "monto_exento"
    t.integer "monto_iva"
    t.integer "monto_total"
    t.integer "impuestos"
    t.string "fecha_vencimiento"
  end

  create_table "horas", force: :cascade do |t|
    t.date "fecha"
    t.string "descripcion"
    t.string "area"
    t.string "personal"
    t.time "inicio"
    t.time "termino"
    t.float "he"
    t.integer "ot"
    t.string "traslado"
    t.string "lugar"
    t.string "mandante"
    t.string "estado"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "ep"
  end

  create_table "interventions", force: :cascade do |t|
    t.string "equipo"
    t.datetime "desde"
    t.datetime "hasta"
    t.string "mecanico"
    t.text "descripcion"
    t.string "repuestos"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.bigint "truck_id"
    t.integer "duracion"
    t.index ["truck_id"], name: "index_interventions_on_truck_id"
  end

  create_table "mantencions", force: :cascade do |t|
    t.string "equipo"
    t.datetime "desde"
    t.datetime "hasta"
    t.string "mecanico"
    t.text "descripcion"
    t.string "repuestos"
    t.bigint "truck_id"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["truck_id"], name: "index_mantencions_on_truck_id"
  end

  create_table "medidas", force: :cascade do |t|
    t.integer "silo19a"
    t.integer "silo19b"
    t.integer "silo20a"
    t.integer "silo20b"
    t.integer "silo21a"
    t.integer "silo21b"
    t.integer "silo22a"
    t.integer "silo22b"
    t.integer "silo27"
    t.integer "silo28"
    t.integer "especialsacos"
    t.integer "extrsacos"
    t.integer "bigbagextra"
    t.integer "bigbagextra1350"
    t.integer "bigbagextra1"
    t.integer "bigbagespecial"
    t.integer "bigbagsuper"
    t.integer "prodhaver"
    t.integer "prodvento"
    t.string "tolvacalle5"
    t.string "silos3000tolva1"
    t.string "silos3000tolva4"
    t.string "silos3000tolva5"
    t.string "silosbigbag1"
    t.string "silosbigbag2"
    t.string "silosvento1"
    t.string "silovento2"
    t.string "silovento3"
    t.integer "callesilo28"
    t.integer "callesplanta1"
    t.integer "callesilo27"
    t.string "observaciones"
    t.integer "otros"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.integer "ns28"
    t.integer "nbb1"
    t.integer "nbb2"
    t.integer "nvento1"
    t.integer "nvento2"
    t.integer "nvento3"
    t.integer "ns30001"
    t.integer "ns30002"
    t.integer "ns30003"
    t.integer "nivel9"
    t.integer "bigbagplus"
    t.string "s28c3op"
    t.string "s28c3cemento"
    t.string "s28c3nota"
    t.string "s28c4op"
    t.string "s28c4cemento"
    t.string "s28c4nota"
    t.string "s28c5op"
    t.string "s28c5cemento"
    t.string "s28c5nota"
    t.string "s27c6op"
    t.string "s27c7cemento"
    t.string "s27c7nota"
    t.string "s30c1op"
    t.string "s30c1cemento"
    t.string "s30c1nota"
    t.string "s30c4op"
    t.string "s30c4cemento"
    t.string "s30c4nota"
    t.string "s30c5op"
    t.string "s30c5cemento"
    t.string "s30c5nota"
    t.integer "plastificado_especial"
    t.integer "plastificado_especial_lados"
    t.integer "plastificado_extra"
    t.integer "plastificado_extra_zunchos"
    t.integer "plastificado_especial_zunchos"
    t.integer "especial_sacos"
    t.integer "especial_bigbag"
    t.integer "especial_granel"
    t.integer "extra_sacos"
    t.integer "extra_bigbag"
    t.integer "extra_granel"
    t.integer "super_3300_granel"
    t.integer "super_4200_granel"
    t.integer "enjuagues_super"
    t.integer "enjuagues_super4"
    t.integer "bigbag_extra_retiro"
    t.integer "plastificado_especial_soluble_completo"
    t.integer "plastificado_extra_soluble_completo"
    t.integer "especial_sacos_soluble"
    t.integer "extra_sacos_soluble"
  end

  create_table "overtimes", force: :cascade do |t|
    t.datetime "inicio"
    t.datetime "termino"
    t.bigint "personal_id", null: false
    t.integer "cantidad"
    t.text "motivo"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["personal_id"], name: "index_overtimes_on_personal_id"
  end

  create_table "permisos", force: :cascade do |t|
    t.date "desde"
    t.date "hasta"
    t.integer "cantidad"
    t.integer "periodo"
    t.string "otros"
    t.bigint "personal_id", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["personal_id"], name: "index_permisos_on_personal_id"
  end

  create_table "personals", force: :cascade do |t|
    t.integer "rut"
    t.integer "dv"
    t.string "nombre"
    t.date "contratado"
    t.string "evaluacion"
    t.string "comentarios"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "reports", force: :cascade do |t|
    t.integer "especial_sacos"
    t.integer "extra_sacos"
    t.integer "especial_soluble"
    t.integer "extra_soluble"
    t.integer "bb_especial"
    t.integer "bb_extra"
    t.integer "prod_esp_sacos"
    t.integer "prod_extra_sacos"
    t.integer "prod_extra_soluble"
    t.integer "prod_esp_bb"
    t.integer "prod_extra_bb"
    t.integer "envases_esp"
    t.integer "envases_ext"
    t.integer "envases_bb"
    t.integer "pallets_buenos"
    t.integer "muestra_pallets"
    t.integer "humedad_promedio"
    t.integer "bobinas"
    t.text "observaciones"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "requerimientos", force: :cascade do |t|
    t.string "nombre"
    t.string "planta"
    t.string "solicitud"
    t.text "observaciones"
    t.text "respuesta"
    t.string "otros"
    t.integer "monto"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "phone"
    t.string "estado"
    t.string "contact"
  end

  create_table "servicios", force: :cascade do |t|
    t.integer "cas"
    t.integer "nfu"
    t.integer "apoyo_cas"
    t.integer "kkbc_a_p2"
    t.integer "kka_a_ngp"
    t.integer "kka_a_p1"
    t.integer "yeso_a_silo"
    t.integer "conchuela_a_bru"
    t.integer "escombros"
    t.integer "residuos"
    t.integer "barrido_industrial"
    t.string "retiro_derrames"
    t.integer "aspirado"
    t.integer "cementos"
    t.integer "transportador"
    t.integer "materia_prima"
    t.integer "harneo_o_seleccion"
    t.integer "recarga"
    t.integer "molino"
    t.integer "descarga"
    t.integer "ton"
    t.integer "lavado_cont"
    t.integer "retiro_escombros"
    t.string "cloracion"
    t.integer "ol01"
    t.integer "ol02"
    t.integer "ol09"
    t.integer "ol10"
    t.integer "ex01"
    t.integer "ok05"
    t.integer "ok04"
    t.integer "barr12"
    t.integer "bbc20"
    t.integer "h12"
    t.integer "ca"
    t.text "comentarios"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "soplados", force: :cascade do |t|
    t.string "supervisor"
    t.datetime "fecha"
    t.float "presion1"
    t.float "presion2"
    t.float "presion3"
    t.string "observaciones"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.float "horno"
    t.float "presion4"
    t.float "presion5"
    t.float "presion6"
    t.boolean "jetin"
    t.string "mirillas"
    t.float "so3"
  end

  create_table "trabajos", force: :cascade do |t|
    t.string "planta"
    t.string "ito"
    t.string "descripcion"
    t.integer "total"
    t.date "fecha_termino"
    t.string "avance"
    t.integer "op"
    t.integer "factura"
    t.string "observaciones"
    t.string "i1"
    t.string "i2"
    t.string "i3"
    t.string "i4"
    t.string "i5"
    t.string "i6"
    t.string "i7"
    t.string "i8"
    t.string "i9"
    t.string "i10"
    t.string "i11"
    t.string "i12"
    t.integer "v1"
    t.integer "v2"
    t.integer "v3"
    t.integer "v4"
    t.integer "v5"
    t.integer "v6"
    t.integer "v7"
    t.integer "v8"
    t.integer "v9"
    t.integer "v10"
    t.integer "v11"
    t.integer "v12"
    t.string "centro_costo"
    t.string "supervisor"
    t.string "otros"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "q1"
    t.integer "q2"
    t.integer "q3"
    t.integer "q4"
    t.integer "q5"
    t.integer "q6"
    t.integer "q7"
    t.integer "q8"
    t.integer "q9"
    t.integer "q10"
    t.integer "q11"
    t.integer "q12"
    t.string "detalle"
  end

  create_table "trucks", force: :cascade do |t|
    t.string "codigo"
    t.string "marca"
    t.string "modelo"
    t.string "planta"
    t.integer "año"
    t.text "otros"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "units", force: :cascade do |t|
    t.string "o11"
    t.string "o12"
    t.string "o13"
    t.string "o14"
    t.string "o15"
    t.string "o16"
    t.string "o17"
    t.integer "o18"
    t.string "o21"
    t.string "o22"
    t.string "o23"
    t.string "o24"
    t.string "o25"
    t.string "o26"
    t.string "o27"
    t.integer "o28"
    t.string "o31"
    t.string "o32"
    t.string "o33"
    t.string "o34"
    t.string "o35"
    t.string "o36"
    t.string "o37"
    t.integer "o38"
    t.string "o41"
    t.string "o42"
    t.string "o43"
    t.string "o44"
    t.string "o45"
    t.string "o46"
    t.string "o47"
    t.integer "o48"
    t.string "o51"
    t.string "o52"
    t.string "o53"
    t.string "o54"
    t.string "o55"
    t.string "o56"
    t.string "o57"
    t.string "o58"
    t.string "o61"
    t.string "o62"
    t.string "o63"
    t.string "o64"
    t.string "o65"
    t.string "o66"
    t.string "o67"
    t.integer "o68"
    t.string "o71"
    t.string "o72"
    t.string "o73"
    t.string "o74"
    t.string "o75"
    t.string "o76"
    t.string "o77"
    t.integer "o78"
    t.string "o81"
    t.string "o82"
    t.string "o83"
    t.string "o84"
    t.string "o85"
    t.string "o86"
    t.string "o87"
    t.integer "o88"
    t.string "b11"
    t.string "b12"
    t.string "b13"
    t.string "b14"
    t.string "b15"
    t.string "b16"
    t.string "b17"
    t.integer "b18"
    t.string "b21"
    t.string "b22"
    t.string "b23"
    t.string "b24"
    t.string "b25"
    t.string "b26"
    t.string "b27"
    t.integer "b28"
    t.string "b31"
    t.string "b32"
    t.string "b33"
    t.string "b34"
    t.string "b35"
    t.string "b36"
    t.string "b37"
    t.integer "b38"
    t.string "b41"
    t.string "b42"
    t.string "b43"
    t.string "b44"
    t.string "b45"
    t.string "b46"
    t.string "b47"
    t.integer "b48"
    t.string "b51"
    t.string "b52"
    t.string "b53"
    t.string "b54"
    t.string "b55"
    t.string "b56"
    t.string "b57"
    t.integer "b58"
    t.string "b61"
    t.string "b62"
    t.string "b63"
    t.string "b64"
    t.string "b65"
    t.string "b66"
    t.string "b67"
    t.integer "b68"
    t.string "b71"
    t.string "b72"
    t.string "b73"
    t.string "b74"
    t.string "b75"
    t.string "b76"
    t.string "b77"
    t.integer "b78"
    t.string "h11"
    t.string "h12"
    t.string "h13"
    t.string "h14"
    t.string "h15"
    t.string "h16"
    t.string "h17"
    t.integer "h18"
    t.string "h21"
    t.string "h22"
    t.string "h23"
    t.string "h24"
    t.string "h25"
    t.string "h26"
    t.string "h27"
    t.integer "h28"
    t.string "h31"
    t.string "h32"
    t.string "h33"
    t.string "h34"
    t.string "h35"
    t.string "h36"
    t.string "h37"
    t.integer "h38"
    t.string "h41"
    t.string "h42"
    t.string "h43"
    t.string "h44"
    t.string "h45"
    t.string "h46"
    t.string "h47"
    t.integer "h48"
    t.string "h51"
    t.string "h52"
    t.string "h53"
    t.string "h54"
    t.string "h55"
    t.string "h56"
    t.string "h57"
    t.integer "h58"
    t.string "h61"
    t.string "h62"
    t.string "h63"
    t.string "h64"
    t.string "h65"
    t.string "h66"
    t.string "h67"
    t.integer "h68"
    t.string "h71"
    t.string "h72"
    t.string "h73"
    t.string "h74"
    t.string "h75"
    t.string "h76"
    t.string "h77"
    t.integer "h78"
    t.text "observaciones"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.boolean "superadmin_role", default: false
    t.boolean "supervisor_role", default: false
    t.boolean "user_role", default: true
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  create_table "vtslimpiezas", force: :cascade do |t|
    t.string "nombre"
    t.datetime "fecha"
    t.string "turno"
    t.string "pesamatic"
    t.string "camarin"
    t.string "baño"
    t.string "comedor"
    t.string "botoneras"
    t.string "baranda"
    t.string "asiento"
    t.string "mesa_computador"
    t.string "mesa_comedor"
    t.string "comentarios"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  add_foreign_key "checklists", "trucks"
  add_foreign_key "equipos", "trucks"
  add_foreign_key "interventions", "trucks"
  add_foreign_key "mantencions", "trucks"
  add_foreign_key "overtimes", "personals"
  add_foreign_key "permisos", "personals"
end
