class CreateEnvasadoras < ActiveRecord::Migration[6.0]
  def change
    create_table :envasadoras do |t|
      t.integer :stock_sacosespecial
      t.integer :stock_sacosextra
      t.integer :stock_bigbagespaecial
      t.integer :stock_bigbagextra
      t.integer :stock_bigbagplus
      t.integer :stock_bigbagsuper
      t.integer :produccion_haver
      t.integer :horas_disphaver
      t.integer :horas_efectivahaver
      t.integer :produccion_ventomatic
      t.integer :horas_dispventomatic
      t.integer :horas_efectivaventomatic
      t.integer :programa_especialsacos
      t.integer :programa_extrasacos
      t.integer :programa_especialbigbag
      t.integer :programa_extrabigbag
      t.integer :programa_extrabigbag1t
      t.integer :programa_plusbigbag
      t.integer :programa_superbigbag
      t.integer :despacho_especialsacos
      t.integer :despacho_extrasacos
      t.integer :despacho_especialbigbag
      t.integer :despacho_extrabigbag
      t.integer :despacho_extrabigbag1t
      t.integer :despacho_plusbigbag
      t.integer :despacho_superbigbag
      t.integer :medida1_silo19
      t.integer :medida2_silo19
      t.integer :medida1_silo20
      t.integer :medida2_silo20
      t.integer :medida1_silo21
      t.integer :medida2_silo21
      t.integer :medida1_silo22
      t.integer :medida2_silo22
      t.integer :medida_silo27
      t.integer :medida_silo28
      t.integer :medida_tolva5s28
      t.integer :medida_tolva1vento
      t.integer :medida_tolva2vento
      t.integer :medida_tolva3vento
      t.integer :medida_tolva1bigbag
      t.integer :medida_tolva2bigbag
      t.integer :medida_tolva1s3000
      t.integer :medida_tolva4s3000
      t.string :medida_tolva5s3000
      t.string :producto_tolva5s28
      t.string :producto_tolva1vento
      t.string :producto_tolva2vento
      t.string :producto_tolva3vento
      t.string :producto_tolva1bigbag
      t.string :producto_tolva2bigbag
      t.string :producto_tolva1s3000
      t.string :producto_tolva4s3000
      t.string :producto_tolva5s3000
      t.integer :programa_manthaver
      t.integer :ejecutado_manthaver
      t.integer :programa_mantvento
      t.integer :ejecutado_mantvento
      t.integer :programa_mantbigbag
      t.integer :ejecutado_mantbigbag
      t.integer :programa_mantgranel
      t.integer :ejecutado_mantgranel
      t.integer :programa_mantplanta1
      t.integer :ejecutado_mantplanta1
      t.integer :programa_mantenv
      t.integer :ejecutado_mantenv
      t.integer :adicional_manthaver
      t.integer :adicional_mantvento
      t.integer :adicional_mantbigbbag
      t.string :adicional_mantgranel
      t.integer :adicional_mantp1
      t.integer :adicional_mantenv
      t.string :obs_manthaver
      t.string :obs_mantvento
      t.string :obs_mantbigbag
      t.string :obs_mantgranel
      t.string :obs_mantp1
      t.string :obs_mantenv
      t.string :linea_tarearelevante
      t.string :ot_tarearelevante
      t.string :descripcion_tarearelevante
      t.string :tipo_fallarelevante
      t.integer :hora_fallarelevante
      t.string :descripcion_fallarelevante
      t.integer :descarga_materiaprima
      t.integer :respaldo_descargamateriaprima
      t.integer :excavadora
      t.integer :camion_tolva
      t.integer :barredora
      t.integer :bobcat
      t.integer :horquilla_serv
      t.integer :horquilla_haver
      t.integer :horquilla_vento
      t.integer :horquilla_cargabigbag
      t.integer :horquilla_llenadobigbag
      t.integer :horquilla_respaldo7t
      t.integer :horquilla_respaldo3t
      t.integer :cargador_descargacaliza
      t.integer :cargador_descargapuzolana
      t.integer :cargador_respaldo
      t.integer :cargador_patio
      t.text :observaciones
      t.date :fecha
      t.string :observacion_prodhaver
      t.string :observacion_prodvento
      t.integer :num_adicional
      t.integer :num_adicional2
      t.integer :num_adicional3
      t.string :adicional

      t.timestamps
    end
  end
end
