class CreateUnits < ActiveRecord::Migration[6.1]
  def change
    create_table :units do |t|
      t.string :o11
      t.string :o12
      t.string :o13
      t.string :o14
      t.string :o15
      t.string :o16
      t.string :o17
      t.integer :o18
      t.string :o21
      t.string :o22
      t.string :o23
      t.string :o24
      t.string :o25
      t.string :o26
      t.string :o27
      t.integer :o28
      t.string :o31
      t.string :o32
      t.string :o33
      t.string :o34
      t.string :o35
      t.string :o36
      t.string :o37
      t.integer :o38
      t.string :o41
      t.string :o42
      t.string :o43
      t.string :o44
      t.string :o45
      t.string :o46
      t.string :o47
      t.integer :o48
      t.string :o51
      t.string :o52
      t.string :o53
      t.string :o54
      t.string :o55
      t.string :o56
      t.string :o57
      t.string :o58
      t.string :o61
      t.string :o62
      t.string :o63
      t.string :o64
      t.string :o65
      t.string :o66
      t.string :o67
      t.integer :o68
      t.string :o71
      t.string :o72
      t.string :o73
      t.string :o74
      t.string :o75
      t.string :o76
      t.string :o77
      t.integer :o78
      t.string :o81
      t.string :o82
      t.string :o83
      t.string :o84
      t.string :o85
      t.string :o86
      t.string :o87
      t.integer :o88
      t.string :b11
      t.string :b12
      t.string :b13
      t.string :b14
      t.string :b15
      t.string :b16
      t.string :b17
      t.integer :b18
      t.string :b21
      t.string :b22
      t.string :b23
      t.string :b24
      t.string :b25
      t.string :b26
      t.string :b27
      t.integer :b28
      t.string :b31
      t.string :b32
      t.string :b33
      t.string :b34
      t.string :b35
      t.string :b36
      t.string :b37
      t.integer :b38
      t.string :b41
      t.string :b42
      t.string :b43
      t.string :b44
      t.string :b45
      t.string :b46
      t.string :b47
      t.integer :b48
      t.string :b51
      t.string :b52
      t.string :b53
      t.string :b54
      t.string :b55
      t.string :b56
      t.string :b57
      t.integer :b58
      t.string :b61
      t.string :b62
      t.string :b63
      t.string :b64
      t.string :b65
      t.string :b66
      t.string :b67
      t.integer :b68
      t.string :b71
      t.string :b72
      t.string :b73
      t.string :b74
      t.string :b75
      t.string :b76
      t.string :b77
      t.integer :b78
      t.string :h11
      t.string :h12
      t.string :h13
      t.string :h14
      t.string :h15
      t.string :h16
      t.string :h17
      t.integer :h18
      t.string :h21
      t.string :h22
      t.string :h23
      t.string :h24
      t.string :h25
      t.string :h26
      t.string :h27
      t.integer :h28
      t.string :h31
      t.string :h32
      t.string :h33
      t.string :h34
      t.string :h35
      t.string :h36
      t.string :h37
      t.integer :h38
      t.string :h41
      t.string :h42
      t.string :h43
      t.string :h44
      t.string :h45
      t.string :h46
      t.string :h47
      t.integer :h48
      t.string :h51
      t.string :h52
      t.string :h53
      t.string :h54
      t.string :h55
      t.string :h56
      t.string :h57
      t.integer :h58
      t.string :h61
      t.string :h62
      t.string :h63
      t.string :h64
      t.string :h65
      t.string :h66
      t.string :h67
      t.integer :h68
      t.string :h71
      t.string :h72
      t.string :h73
      t.string :h74
      t.string :h75
      t.string :h76
      t.string :h77
      t.integer :h78
      t.text :observaciones

      t.timestamps
    end
  end
end
